name: PR Action Checks
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  backend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Run all sh files in /tests
      - name: Run test scripts
        run: |
          for file in tests/*.sh; do
            echo "Running $file"
            bash $file
          done
